services:
  db:
    container_name: envctl-db
    image: postgres:15
    environment:
      POSTGRES_DB: envctl
      POSTGRES_USER: envctl
      POSTGRES_PASSWORD: envctl
    ports:
      - "5432:5432"